/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import static org.junit.Assert.*;

import org.junit.Test;

class AppTest {
  @Test void appHasGreeting() {
    App classUnderTest = new App();
    assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
  }
}
